"""Code generation: discrete state space -> RNM-ready HDL and reference models.

Sign / unit convention used everywhere below
--------------------------------------------
    u = current injected INTO the port  [A]
    y = port voltage response           [V]      y = Z(s) u

A load that DRAWS current is a negative u.  The convenience wrapper
`<name>_rail` flips that for you and adds the nominal rail voltage:

    v_rail = VNOM - Z * i_load

so a positive `i_load` produces a droop, which is what you want when hooking
this up to an RNM load model.
"""
from __future__ import annotations

import datetime
import json
import textwrap

import numpy as np

from .statespace import block_structure

__all__ = ["emit_systemverilog", "emit_verilogams", "emit_c", "emit_python",
           "emit_json", "emit_sv_testbench"]


def _g(x):
    """Full-precision literal that stays a real in every simulator."""
    v = float(x)
    if v == 0.0:
        return "0.0"
    s = repr(v)
    if "e" not in s and "E" not in s and "." not in s:
        s += ".0"
    return s


def _banner(dss, meta, comment="//"):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "Generated by sp2ss -- S-parameter to state-space for RNM simulation",
        f"generated      : {now}",
        f"source         : {meta.get('source', '?')}",
        f"parameter      : {meta.get('param', 'Z')}  ({meta.get('n_ports', '?')}-port)",
        f"fit order      : {meta.get('fit_order', '?')} poles"
        f" -> {dss.n_states} states after reduction",
        f"fit band       : {meta.get('fmin', 0):.6g} .. {meta.get('fmax', 0):.6g} Hz",
        f"fit error      : max {meta.get('max_rel', float('nan')):.3e} rel,"
        f" rms {meta.get('rms_rel', float('nan')):.3e} rel",
        f"passive        : {meta.get('passive', '?')}",
        f"timestep TS    : {dss.Ts:.6g} s  ({1.0/dss.Ts:.6g} Hz sample rate)",
        f"discretization : {dss.method}",
        f"spectral radius: {dss.spectral_radius():.9f}  (must be < 1)",
        "",
        "u = current injected into the port [A];  y = port voltage [V];  y = Z*u",
        "Drive this at a FIXED period of exactly TS. Changing the sample rate",
        "without re-running sp2ss invalidates the model.",
    ]
    return "\n".join(f"{comment} {ln}".rstrip() for ln in lines)


# ------------------------------------------------------------ SystemVerilog

def emit_systemverilog(dss, name="pdn_ss", meta=None, unroll=True):
    meta = meta or {}
    n, np_ = dss.n_states, dss.n_ports
    ny = dss.Cd.shape[0]
    sizes, is_block = block_structure(dss.Ad)
    if not is_block:
        sizes = [n]

    L = [_banner(dss, meta), "", "`timescale 1ps/1ps", ""]
    L.append(f"module {name} #(")
    L.append(f"    parameter real TS = {_g(dss.Ts)}   // sample period [s] -- informational")
    L.append(") (")
    L.append("    input  wire         clk,      // sample clock, period == TS")
    L.append("    input  wire         rst_n,    // active-low async reset")
    for j in range(np_):
        L.append(f"    input  real         i_p{j},     // current injected into port {j} [A]")
    for i in range(ny):
        tail = "," if i < ny - 1 else ""
        L.append(f"    output real         v_p{i}{tail}      // port {i} voltage [V]")
    L.append(");")
    L.append("")
    L.append(f"    localparam int N_STATES = {n};")
    L.append(f"    localparam int N_PORTS  = {np_};")
    L.append("")

    for i in range(n):
        L.append(f"    real x{i};")
    has_e = dss.Ee is not None
    if has_e:
        L.append("")
        L.append("    // previous-sample currents, for the series-inductance branch")
        for j in range(np_):
            L.append(f"    real i_p{j}_d;")
    L.append("")

    # ---- output equation: y = Cd x + Dd u  (uses x[n], u[n]) --------------
    L.append("    // ---- output:  v = Cd*x + Dd*i  ------------------------------------")
    for i in range(ny):
        terms = [(dss.Cd[i, k], f"x{k}") for k in range(n)]
        terms += [(dss.Dd[i, j], f"i_p{j}") for j in range(np_)]
        if has_e:
            terms += [(dss.Ee[i, j] / dss.Ts, f"(i_p{j} - i_p{j}_d)")
                      for j in range(np_)]
        L.append(f"    assign v_p{i} = " + _sum_expr(terms, 18) + ";")
    if has_e:
        Lp = np.array2string(dss.Ee * 1e12, precision=4).replace("\n", " ")
        L.append(f"    // the (i - i_d)/TS terms above are the series port "
                 f"inductance L = {Lp} pH")
    L.append("")

    L.append("    // ---- state update:  x <= Ad*x + Bd*i  ----------------------------")
    L.append("    // Ad is block-diagonal (real modal form): "
             f"{sizes.count(1)} 1x1 and {sizes.count(2)} 2x2 blocks."
             if is_block else "    // Ad is dense.")
    L.append("    always_ff @(posedge clk or negedge rst_n) begin")
    L.append("        if (!rst_n) begin")
    for i in range(n):
        L.append(f"            x{i} <= 0.0;")
    if has_e:
        for j in range(np_):
            L.append(f"            i_p{j}_d <= 0.0;")
    L.append("        end else begin")
    for i in range(n):
        terms = [(dss.Ad[i, k], f"x{k}") for k in range(n)]
        terms += [(dss.Bd[i, j], f"i_p{j}") for j in range(np_)]
        L.append(f"            x{i} <= " + _sum_expr(terms, 18) + ";")
    if has_e:
        for j in range(np_):
            L.append(f"            i_p{j}_d <= i_p{j};")
    L.append("        end")
    L.append("    end")
    L.append("")
    L.append("endmodule")
    L.append("")

    # ---- rail wrapper ----------------------------------------------------
    L.append(_rail_wrapper_sv(name, np_, ny))
    return "\n".join(L)


def _sum_expr(terms, indent, width=86):
    """Assemble a signed sum from (coefficient, expression) pairs.

    Emits `a*x0 - b*x1 + c*x2`, wrapping onto continuation lines.  Sign handling
    is done here rather than by patching up a joined string, which is how
    `+- ` artefacts creep into generated HDL.
    """
    terms = [(float(c), e) for c, e in terms if float(c) != 0.0]
    if not terms:
        return "0.0"
    pad = " " * (indent + 4)
    out, cur = [], ""
    for k, (c, e) in enumerate(terms):
        if k == 0:
            piece = f"{_g(c)}*{e}"
        else:
            op = "-" if c < 0 else "+"
            piece = f" {op} {_g(abs(c))}*{e}"
        if cur and len(cur) + len(piece) > width:
            out.append(cur)
            cur = pad + piece.lstrip()
            if not piece.lstrip().startswith(("+", "-")):
                cur = pad + piece.strip()
        else:
            cur += piece
    out.append(cur)
    return "\n".join(out)


def _rail_wrapper_sv(name, np_, ny):
    L = ["// ---------------------------------------------------------------------",
         "// Convenience wrapper: load current (drawn, positive) -> rail voltage.",
         "//     v_rail = VNOM - Z * i_load",
         "// ---------------------------------------------------------------------",
         f"module {name}_rail #(",
         "    parameter real VNOM = 1.0,",
         "    parameter real TS   = 1.0e-12",
         ") (",
         "    input  wire         clk,",
         "    input  wire         rst_n,"]
    for j in range(np_):
        L.append(f"    input  real         i_load{j},   // current drawn at port {j} [A]")
    for i in range(ny):
        tail = "," if i < ny - 1 else ""
        L.append(f"    output real         v_rail{i}{tail}")
    L.append(");")
    for i in range(ny):
        L.append(f"    real dv{i};")
    L.append("")
    L.append(f"    {name} #(.TS(TS)) u_core (")
    L.append("        .clk(clk), .rst_n(rst_n),")
    L.append("        " + ", ".join(f".i_p{j}(-i_load{j})" for j in range(np_)) + ",")
    L.append("        " + ", ".join(f".v_p{i}(dv{i})" for i in range(ny)))
    L.append("    );")
    for i in range(ny):
        L.append(f"    assign v_rail{i} = VNOM + dv{i};")
    L.append("endmodule")
    return "\n".join(L)


# ------------------------------------------------------------ Verilog-AMS

def emit_verilogams(dss, name="pdn_ss", meta=None):
    """wreal RNM flavour, self-clocked from an absdelay-free timer."""
    meta = meta or {}
    n, np_ = dss.n_states, dss.n_ports
    ny = dss.Cd.shape[0]
    L = [_banner(dss, meta), "", '`include "disciplines.vams"', "", "`timescale 1ps/1ps", ""]
    L.append(f"module {name}_vams (")
    L.append("    " + ", ".join([f"i_p{j}" for j in range(np_)] +
                                [f"v_p{i}" for i in range(ny)]) + ");")
    L.append("")
    L.append(f"    parameter real TS = {_g(dss.Ts)} from (0:inf);")
    for j in range(np_):
        L.append(f"    input  wreal i_p{j};")
    for i in range(ny):
        L.append(f"    output wreal v_p{i};")
    L.append("")
    L.append(f"    real x[0:{n-1}];")
    L.append(f"    real xn[0:{n-1}];")
    L.append(f"    real u[0:{np_-1}];")
    L.append(f"    real y[0:{ny-1}];")
    L.append("    integer k;")
    L.append("")
    L.append(f"    localparam integer N = {n};")
    L.append("")
    L.append("    // Ad, Bd, Cd, Dd as constant arrays")
    L.append(_vams_const_matrix("AD", dss.Ad))
    L.append(_vams_const_matrix("BD", dss.Bd))
    L.append(_vams_const_matrix("CD", dss.Cd))
    L.append(_vams_const_matrix("DD", dss.Dd))
    if dss.Ee is not None:
        L.append(_vams_const_matrix("EE", dss.Ee / dss.Ts))
        L.append(f"    real ud[0:{np_-1}];")
    L.append("")
    L.append("    analog begin")
    L.append("        @(initial_step) begin")
    L.append("            for (k = 0; k < N; k = k + 1) x[k] = 0.0;")
    if dss.Ee is not None:
        for j in range(np_):
            L.append(f"            ud[{j}] = 0.0;")
    L.append("        end")
    L.append("        @(timer(0, TS)) begin")
    for j in range(np_):
        L.append(f"            u[{j}] = i_p{j};")
    L.append("            // y = Cd*x + Dd*u")
    for i in range(ny):
        terms = [f"CD_{i}_{k}*x[{k}]" for k in range(n) if dss.Cd[i, k] != 0.0]
        terms += [f"DD_{i}_{j}*u[{j}]" for j in range(np_) if dss.Dd[i, j] != 0.0]
        if dss.Ee is not None:
            terms += [f"EE_{i}_{j}*(u[{j}] - ud[{j}])" for j in range(np_)
                      if dss.Ee[i, j] != 0.0]
        L.append(f"            y[{i}] = " + (" + ".join(terms) or "0.0") + ";")
    L.append("            // x <= Ad*x + Bd*u")
    for i in range(n):
        terms = [f"AD_{i}_{k}*x[{k}]" for k in range(n) if dss.Ad[i, k] != 0.0]
        terms += [f"BD_{i}_{j}*u[{j}]" for j in range(np_) if dss.Bd[i, j] != 0.0]
        L.append(f"            xn[{i}] = " + (" + ".join(terms) or "0.0") + ";")
    L.append("            for (k = 0; k < N; k = k + 1) x[k] = xn[k];")
    if dss.Ee is not None:
        for j in range(np_):
            L.append(f"            ud[{j}] = u[{j}];")
    L.append("        end")
    for i in range(ny):
        L.append(f"        v_p{i} <+ y[{i}];")
    L.append("    end")
    L.append("endmodule")
    return "\n".join(L)


def _vams_const_matrix(tag, M):
    out = []
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            if M[i, j] != 0.0:
                out.append(f"    localparam real {tag}_{i}_{j} = {_g(M[i, j])};")
    return "\n".join(out)


# ------------------------------------------------------------ C / Python

def emit_c(dss, name="pdn_ss", meta=None):
    meta = meta or {}
    n, np_ = dss.n_states, dss.n_ports
    ny = dss.Cd.shape[0]

    def arr(M):
        rows = [", ".join(_g(v) for v in r) for r in np.atleast_2d(M)]
        return "{\n    {" + "},\n    {".join(rows) + "}\n}"

    src = f"""{_banner(dss, meta, '//')}

#include <string.h>

#define {name.upper()}_N      {n}
#define {name.upper()}_NPORT  {np_}
#define {name.upper()}_NOUT   {ny}
static const double {name}_TS = {_g(dss.Ts)};

static const double AD[{n}][{n}] = {arr(dss.Ad)};
static const double BD[{n}][{np_}] = {arr(dss.Bd)};
static const double CD[{ny}][{n}] = {arr(dss.Cd)};
static const double DD[{ny}][{np_}] = {arr(dss.Dd)};
{("static const double EE[%d][%d] = %s;   /* E/Ts, series port inductance */"
  % (ny, np_, arr(dss.Ee / dss.Ts))) if dss.Ee is not None else ""}

typedef struct {{ double x[{n}];{" double ud[%d];" % np_ if dss.Ee is not None else ""} }} {name}_state;

void {name}_reset({name}_state *st) {{ memset(st, 0, sizeof(*st)); }}

/* One timestep. u = current injected into each port [A]; y = port voltage [V].
   Call at a fixed period of {name}_TS seconds. */
void {name}_step({name}_state *st, const double *u, double *y)
{{
    double xn[{n}];
    int i, k;
    for (i = 0; i < {ny}; ++i) {{
        double acc = 0.0;
        for (k = 0; k < {n}; ++k)  acc += CD[i][k] * st->x[k];
        for (k = 0; k < {np_}; ++k) acc += DD[i][k] * u[k];
{"        for (k = 0; k < %d; ++k) acc += EE[i][k] * (u[k] - st->ud[k]);" % np_ if dss.Ee is not None else ""}
        y[i] = acc;
    }}
    for (i = 0; i < {n}; ++i) {{
        double acc = 0.0;
        for (k = 0; k < {n}; ++k)  acc += AD[i][k] * st->x[k];
        for (k = 0; k < {np_}; ++k) acc += BD[i][k] * u[k];
        xn[i] = acc;
    }}
    memcpy(st->x, xn, sizeof(xn));
{"    memcpy(st->ud, u, sizeof(st->ud));" if dss.Ee is not None else ""}
}}
"""
    return src


def emit_python(dss, name="pdn_ss", meta=None):
    meta = meta or {}
    body = f'''"""{name} -- discrete PDN macromodel (reference implementation).

{_banner(dss, meta, '#').replace(chr(10) + '# ', chr(10))}
"""
import numpy as np

TS = {_g(dss.Ts)}
AD = np.array({np.array2string(dss.Ad, separator=", ", threshold=10**9, precision=17, max_line_width=100)})
BD = np.array({np.array2string(dss.Bd, separator=", ", threshold=10**9, precision=17, max_line_width=100)})
CD = np.array({np.array2string(dss.Cd, separator=", ", threshold=10**9, precision=17, max_line_width=100)})
DD = np.array({np.array2string(dss.Dd, separator=", ", threshold=10**9, precision=17, max_line_width=100)})
EE = {("np.array(" + np.array2string(dss.Ee / dss.Ts, separator=", ", threshold=10**9, precision=17, max_line_width=100) + ")") if dss.Ee is not None else "None"}   # E/Ts: series port inductance


class {_cls(name)}:
    """x[n+1] = AD x[n] + BD u[n];  y[n] = CD x[n] + DD u[n]."""

    def __init__(self):
        self.x = np.zeros(AD.shape[0])
        self.ud = np.zeros(BD.shape[1])

    def reset(self):
        self.x[:] = 0.0
        self.ud[:] = 0.0

    def step(self, u):
        u = np.atleast_1d(np.asarray(u, float))
        y = CD @ self.x + DD @ u
        if EE is not None:
            y = y + EE @ (u - self.ud)
            self.ud = u.copy()
        self.x = AD @ self.x + BD @ u
        return y

    def run(self, u):
        u = np.atleast_2d(np.asarray(u, float))
        if u.shape[1] != BD.shape[1]:
            u = u.T
        return np.array([self.step(row) for row in u])
'''
    return body


def _cls(name):
    return "".join(p.capitalize() for p in name.split("_")) or "Model"


def emit_json(dss, meta=None):
    meta = dict(meta or {})
    meta = {k: (v.tolist() if isinstance(v, np.ndarray) else v)
            for k, v in meta.items()}
    return json.dumps({
        "Ts": dss.Ts,
        "method": dss.method,
        "n_states": int(dss.n_states),
        "n_ports": int(dss.n_ports),
        "spectral_radius": dss.spectral_radius(),
        "Ad": dss.Ad.tolist(),
        "Bd": dss.Bd.tolist(),
        "Cd": dss.Cd.tolist(),
        "Dd": dss.Dd.tolist(),
        "Ee_over_Ts": (dss.Ee / dss.Ts).tolist() if dss.Ee is not None else None,
        "E_inductance_H": dss.Ee.tolist() if dss.Ee is not None else None,
        "meta": meta,
    }, indent=2)


# ------------------------------------------------------------ testbench

def emit_sv_testbench(dss, name="pdn_ss", meta=None, step_amp=1.0,
                      golden=None):
    """Self-checking testbench: applies a current step and (optionally) compares
    against golden samples produced by the Python reference model."""
    meta = meta or {}
    np_ = dss.n_ports
    ny = dss.Cd.shape[0]
    ts_ps = dss.Ts * 1e12
    L = [f"// Testbench for {name}. Current step of {step_amp} A on port 0.",
         "`timescale 1ps/1ps", "",
         f"module tb_{name};",
         "    reg clk = 0, rst_n = 0;",
         f"    localparam real TS = {_g(dss.Ts)};",
         f"    localparam time  TS_PS = {max(int(round(ts_ps/2)),1)};   // half period in ps",
         "    always #(TS_PS) clk = ~clk;", ""]
    for j in range(np_):
        L.append(f"    real i_p{j} = 0.0;")
    for i in range(ny):
        L.append(f"    real v_p{i};")
    L.append("")
    L.append(f"    {name} #(.TS(TS)) dut (.clk(clk), .rst_n(rst_n), " +
             ", ".join([f".i_p{j}(i_p{j})" for j in range(np_)] +
                       [f".v_p{i}(v_p{i})" for i in range(ny)]) + ");")
    L.append("")
    L.append("    integer n = 0;")
    L.append("    integer fh;")
    L.append("    initial begin")
    L.append(f'        fh = $fopen("{name}_step.csv", "w");')
    L.append('        $fwrite(fh, "n,t_s,' +
             ",".join([f"i_p{j}" for j in range(np_)] +
                      [f"v_p{i}" for i in range(ny)]) + '\\n");')
    L.append("        repeat (4) @(posedge clk);")
    L.append("        rst_n = 1;")
    L.append("        repeat (10) @(posedge clk);")
    L.append(f"        i_p0 = {_g(step_amp)};      // current step into port 0")
    L.append("        repeat (20000) begin")
    L.append("            @(posedge clk);")
    L.append("            #1;")
    L.append('            $fwrite(fh, "%0d,%e,' +
             ",".join(["%e"] * (np_ + ny)) + '\\n", n, n*TS, ' +
             ", ".join([f"i_p{j}" for j in range(np_)] +
                       [f"v_p{i}" for i in range(ny)]) + ");")
    L.append("            n = n + 1;")
    L.append("        end")
    L.append("        $fclose(fh);")
    L.append(f'        $display("[tb_{name}] wrote {name}_step.csv");')
    L.append("        $finish;")
    L.append("    end")
    L.append("endmodule")
    return "\n".join(L)
